var InitialData = {
	"1" : {
		"id": "1",
		"url": "https://www.youtube.com/watch?v=I0o_2qVuC2s",
		"title": "Pulp Kitchen",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": true,	
		"lat": 51.518507,
		"long": -0.120933,
		"open": true,
		"starts": 0,
		"ends": 23,
		"next_item": 3, 
		"category": "edible",
		},
	"2" : {
		"id": "2",
		"url": "https://www.youtube.com/watch?v=D4ldpVKpa9U",
		"title": "Artworks",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.521507,
		"long": -0.121933,
		"open": false,
		"starts": 2,
		"ends": 23,
		"next_item": 3,
		"category": "container",
		
	},
	"3" : {
		"id": "3",
		"url": "https://www.youtube.com/watch?v=26Dmu-AB4a0",
		"title": "Backyard Sequence 1",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.531707,
		"long": -0.121133,
		"open": false,
		"starts": 3,
		"ends": 33,
		"next_item": 4,
		"category": "reel",
	},
	"4" : {
		"id": "4",
		"url": "https://www.youtube.com/watch?v=k6NzHTisRpo",
		"title": "The General's Barber",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.537563, 
		"long": -0.057750,
		"open": false,
		"starts": 4,
		"ends": 24,
		"next_item": 5,
		"category": "container",	
	},
	"5" : {
		"id": "5",
		"url": "https://www.youtube.com/watch?v=49TrYmw5olo",
		"title": "Grow Up",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.541722, 
		"long": -0.114413,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "container",
		},
	"6" : {
		"id": "6",
		"url": "https://www.youtube.com/watch?v=yz12fXpYKdE",
		"title": "Cristabels",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.541722, 
		"long": -0.114413,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "edible",
		},
	"7" : {
		"id": "7",
		"url": "https://www.youtube.com/watch?v=1hs4Xrxj7KM",
		"title": "Ship's Kitchen",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.541722, 
		"long": -0.114413,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "edible",
		},
	"8" : {
		"id": "8",
		"url": "https://www.youtube.com/watch?v=fW8UQvPUQbs",
		"title": "Secret Kitchen",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.541722, 
		"long": -0.114413,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "edible",
		},
	"9" : {
		"id": "9",
		"url": "https://www.youtube.com/watch?v=Xa_M1ZtT9-Y",
		"title": "Sarah",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.536054,   
		"long": -0.059745,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "container",
		},
	"10" : {
		"id": "10",
		"url": "https://www.youtube.com/watch?v=ibF41vCwfK4",
		"title": "Egle",
		"blurb": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
		"visible": false,	
		"lat": 51.536054,   
		"long": -0.059745,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "container",
		},



};


module.exports = InitialData;
