var InitialData = {
	"1" : {
		"id": "1",
		"url": "https://www.youtube.com/watch?v=1KkpivEsitE",
		"title": "Pulp Kitchen",
		"blurb": "Tonight, Feed Me Films are running ‘Pulp Kitchen’. A menu of Pulp Fiction inspired drinks and snacks has been designed to immersive viewers in the film’s sensory landscape.",
		"visible": false,	
		"lat": 51.498042, 
		"long": -0.080688,
		"open": true,
		"starts": 1,
		"ends": 23,
		"next_item": 3, 
		"category": "edible",
		},
	"2" : {
		"id": "2",
		"url": "https://www.youtube.com/watch?v=D4ldpVKpa9U",
		"title": "The Artworks",
		"blurb": "The Artworks is a shipping container mall occupying the site of the recently demolished Heygate Housing estate. It is organised and managed by Lend Lease, the company responsible for the site's redevelopment.",
		"visible": false,	
		"lat": 51.493070, 
		"long": -0.101545,
		"open": false,
		"starts": 25,
		"ends": 80,
		"next_item": 3,
		"category": "container",
		
	},
	"3" : {
		"id": "3",
		"url": "https://www.youtube.com/watch?v=26Dmu-AB4a0",
		"title": "Backyard Cinema",
		"blurb": "Backyard Cinema are staging an immersive screening of Baz Lurham’s Romeo and Juliet in St Mary’s Church in Baker Street. The event is staffed by The Montague’s Hawaiian shirt clad gang and accompanied by a live choir.",
		"visible": false,	
		"lat": 51.519374,
		"long": -0.168056,
		"open": false,
		"starts": 3,
		"ends": 33,
		"next_item": 4,
		"category": "reel",
	},
	"4" : {
		"id": "4",
		"url": "https://www.youtube.com/watch?v=k6NzHTisRpo",
		"title": "The General's Barber",
		"blurb": "A barber shop in a container: Hair cuts, beard trims, and free beer.",
		"visible": false,	
		"lat": 51.537563, 
		"long": -0.057750,
		"open": false,
		"starts": 38,
		"ends": 100,
		"next_item": 5,
		"category": "container",	
	},
	"5" : {
		"id": "5",
		"url": "https://www.youtube.com/watch?v=49TrYmw5olo",
		"title": "Grow Up",
		"blurb": "The Grow Up Box is an urban farm in a shipping container. The futuristic mirco-farm is designed to demonstrate the potential of aquaponics for sustainable urban food supply.",
		"visible": false,	
		"lat": 51.513181, 
		"long": 0.013771,
		"open": false,
		"starts": 1,
		"ends": 27,
		"next_item": null,
		"category": "container",
		},
	"6" : {
		"id": "6",
		"url": "https://www.youtube.com/watch?v=yz12fXpYKdE",
		"title": "The Little Yellow Door",
		"blurb": "Christabel is hosting today’s Mad Hatter’s Brunch in a ‘flat-share themed’ bar in Notting Hill. Usually she hosts events in her own flat in east London but today she is branching out to invite 40 guests ‘down the rabbit hole’ with her. The event takes inspiration from Alice and Wonderland, although on that basis it really should be an evening event. In the novel, the Mad Hatter and the March Hare are stuck forever at tea time (6pm), having been accused by the Queen of Hearts of murdering time.",
		"visible": false,	
		"lat": 51.509214,  
		"long": -0.196698,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "edible",
		},
	"7" : {
		"id": "7",
		"url": "https://www.youtube.com/watch?v=1hs4Xrxj7KM",
		"title": "The Ship's Kitchen",
		"blurb": "Sarah, manager of Netil Market, gives her views on the use of shipping containers by East London’s creative community.",
		"visible": false,	
		"lat": 51.531180, 
		"long": 0.073660,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "edible",
		},
	"8" : {
		"id": "8",
		"url": "https://www.youtube.com/watch?v=fW8UQvPUQbs",
		"title": "The Culinary Anthropologist",
		"blurb": "The Culinary Anthropologist: Secret Kitchen - Anna, chef and anthropologist, runs supper clubs from her home in North London. Tonight is a Burns Night themed event.",
		"visible": false,	
		"lat": 51.556585, 
		"long": -0.105167,
		"open": false,
		"starts": 36,
		"ends": 50,
		"next_item": null,
		"category": "edible",
		},
	"9" : {
		"id": "9",
		"url": "https://www.youtube.com/watch?v=Xa_M1ZtT9-Y",
		"title": "Netil Market: Sarah",
		"blurb": "Sarah, manager of Netil Market, gives her views on the use of shipping containers by East London’s creative community.",
		"visible": false,	
		"lat": 51.536054,   
		"long": -0.059745,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "container",
		},
	"10" : {
		"id": "10",
		"url": "https://www.youtube.com/watch?v=ibF41vCwfK4",
		"title": "Egle’s Container Shop",
		"blurb": "Egle and her partner run a gender neutral clothing shop from their container in Netil Market.",
		"visible": false,	
		"lat": 51.536054,   
		"long": -0.059745,
		"open": false,
		"starts": 18,
		"ends": 30,
		"next_item": null,
		"category": "container",
		},
	"11" : {
		"id": "11",
		"url": "https://www.youtube.com/watch?v=IEryyWEIg4s",
		"title": "Floating Cinema: Yannis",
		"blurb": "Floating Cinema are beginning a summer tour from Brentford to Bristol. Yannis is an artist who is accompanying the boat in order to record the sounds of the waterway along the journey. Today he is recording the sounds of Brentford.",
		"visible": false,	
		"lat": 51.489475, 
		"long": -0.234135,
		"open": false,
		"starts": 8,
		"ends": 27,
		"next_item": null,
		"category": "reel",
		},




};


module.exports = InitialData;
