var InitialData = {
	"1": {
		"id": "1",
		"url": "https://www.youtube.com/watch?v=dSqK-laMj7E", // https://www.youtube.com/watch?v=yz12fXpYKdE",
		"title": "The Little Yellow Door",
		"blurb": "Christabel is hosting today’s Mad Hatter’s Brunch in a ‘flat-share themed’ bar in Notting Hill. Usually she hosts events in her own flat in east London but today she is branching out to invite 40 guests ‘down the rabbit hole’ with her. The event takes inspiration from Alice and Wonderland, although on that basis it really should be an evening event. In the novel, the Mad Hatter is stuck forever at tea time (6pm), having been accused by the Queen of Hearts of murdering time.",
		"visible": false,
		"lat": 51.509214,
		"long": -0.196698,
		"open": false,
		"starts": 16,
		"ends": 116,
		"next_item": 9,
		"category": "edible",
		"next_item_title": "Open more of London's closed doors..."
	},
	"2": {
		"id": "2",
		"url": "https://www.youtube.com/watch?v=sPgjndFqqwY", // https://www.youtube.com/watch?v=26Dmu-AB4a0
		"title": "Backyard Cinema",
		"blurb": "Backyard Cinema are staging an immersive screening of Baz Lurham’s Romeo and Juliet in St Mary’s Church in Baker Street. The event is staffed by The Montague’s Hawaiian shirt clad gang and accompanied by a live choir.",
		"visible": true,
		"lat": 51.519374,
		"long": -0.168056,
		"open": false,
		"starts": 0,
		"ends": 100,
		"next_item": 14,
		"category": "reel",
		"next_item_title": "Open more of London's closed doors...",
		"outside_the_hidden": "../images/outside/cinema.jpg",
	},
	"3": {
		"id": "3",
		"url": "https://www.youtube.com/watch?v=fN9iMYOpO_M",
		"title": "Container City",
		"blurb": "Out east along the Thames at Trinity Buoy Warf is container city, a development that is prototypical of London’s many container spaces. The containers, seemingly beached on the banks of the river are being used as offices, cafes, schools or studios. The sounds you can hear are from the floodtide listening post, which converts tidal flow data into notation. ",
		"visible": true,
		"lat": 51.508392,
		"long": 0.007462,
		"open": false,
		"starts": 0,
		"ends": 100,
		"next_item": 11,
		"category": "container",
		"next_item_title": "Follow the river...",
		"outside_the_hidden": "../images/outside/container_city.jpg",
	},
	"4": {
		"id": "4",
		"url": "https://www.youtube.com/watch?v=N5Gp-MgXC3A", // https://www.youtube.com/watch?v=ibF41vCwfK4",
		"title": "Egle’s Container Shop",
		"blurb": "Egle and her partner run a gender neutral clothing shop from their container in Netil Market.",
		"visible": false,
		"lat": 51.536054,
		"long": -0.059745,
		"open": false,
		"starts": 212,
		"ends": 312,
		"next_item": 6,
		"category": "container",
		"next_item_title": "See more ways to customize a container..."
	},
	"5": {
		"id": "5",
		"url": "https://www.youtube.com/watch?v=FONY4SLkv7s", //https://www.youtube.com/watch?v=D4ldpVKpa9U",
		"title": "The Artworks",
		"blurb": "The Artworks is a shipping container mall occupying the site of the recently demolished Heygate Housing estate. It is organised and managed by Lend Lease, the company responsible for the sites redevelopment.",
		"visible": true,
		"lat": 51.49307,
		"long": -0.101545,
		"open": false,
		"starts": 0,
		"ends": 100,
		"next_item": 10,
		"category": "container",
		"next_item_title": "See more ways to customize a container...",
		"outside_the_hidden": "../images/outside/heygate.jpg",
	},
	"6": {
		"id": "6",
		"url": "https://www.youtube.com/watch?v=49TrYmw5olo",
		"title": "Grow up box",
		"blurb": "The Grow Up Box is an urban farm in a shipping container. This futuristic mirco-farm is designed to demonstrate the potential of aquaponics for sustainable urban food supply.",
		"visible": true,
		"lat": 51.514516,
		"long": 0.044842,
		"open": false,
		"starts": 0,
		"ends": 100,
		"next_item": 16,
		"category": "container",
		"next_item_title": "See more ways to customize a container..."
	},
	"7": {
		"id": "7",
		// Short video "url": "https://www.youtube.com/watch?v=jhFDyDgMVUI",
		"url": "https://www.youtube.com/watch?v=FloTVEpRyYY", //https://www.youtube.com/watch?v=fW8UQvPUQbs",
		"title": "The Culinary Anthropologist",
		"blurb": "The Culinary Anthropologist- Secret Kitchen: Anna, chef and anthropologist, runs supper clubs from her home in North London. Tonight is a Burns night themed event.",
		"visible": true,
		"lat": 51.556585,
		"long": -0.105167,
		"open": false,
		"starts": 0,
		"ends": 100,
		"next_item": 10,
		"category": "edible",
		"next_item_title": "Open more of London's closed doors...",
		"outside_the_hidden": "../images/outside/people.jpg",

	},
	"8": {
		"id": "8",
		"url": "https://www.youtube.com/watch?v=gf5HkYBTE9Y", // https://www.youtube.com/watch?v=Xa_M1ZtT9-Y",
		"title": "Netil Market",
		"blurb": "Sarah, manager of Netil Market, gives her views on the use of shipping containers by East London’s creative community.",
		"visible": false,
		"lat": 51.536054,
		"long": -0.059745,
		"open": false,
		"starts": 84,
		"ends": 184,
		"next_item": 15,
		"category": "container",
		"next_item_title": "Explore other transforming urban spaces"
	},
	"9": {
		"id": "9",
		"url": "https://www.youtube.com/watch?v=hB-nrL0YBrg", // https://www.youtube.com/watch?v=1hs4Xrxj7KM",
		"title": "The Ship’s Kitchen",
		"blurb": "Underground Supper club are hosting ‘the ship’s kitchen’, a burns night themed dinner in a converted Dutch barge where Alex, one of the chefs, lives with his girlfriend.",
		"visible": false,
		"lat": 51.53118,
		"long": 0.07366,
		"open": false,
		"starts": 22,
		"ends": 122,
		"next_item": 3,
		"category": "edible",
		"next_item_title": "Follow the river...",
		"outside_the_hidden": "../images/outside/supper_club.jpg",
	},
	"10": {
		"id": "10",
		"url": "https://www.youtube.com/watch?v=bRxdBEe8Lrs", //https://www.youtube.com/watch?v=PLZsG6PIexg",
		"title": "The General’s Barber Shop",
		"blurb": "A barber shop in a container: Hair cuts, beard trims, and free beer.",
		"visible": true,
		"lat": 51.537563,
		"long": -0.05775,
		"open": false,
		"starts": 0,
		"ends": 84,
		"next_item": 15,
		"category": "container",
		"next_item_title": "See more ways to customize a container...",
		"outside_the_hidden": "../images/outside/container_city.jpg"
	},
	"11": {
		"id": "11",
		"url": "https://www.youtube.com/watch?v=MIb0aPgpyHU", // https://www.youtube.com/watch?v=IEryyWEIg4s",
		"title": "Floating Cinema",
		"blurb": "Floating Cinema are beginning a summer tour from Brentford to Bristol. Yannis is the boat's artist in resisdence. He accompanying the boat on its tour in order to record the sounds of the waterway with the help of local people. Today he is recording the sounds of Brentford.",
		"visible": false,
		"lat": 51.489475,
		"long": -0.234135,
		"open": false,
		"starts": 154,
		"ends": 254,
		"next_item": 9,
		"category": "reel",
		"next_item_title": "Follow the river...",
		"outside_the_hidden": "../images/outside/cinema.jpg",
	},
	"13": {
		"id": "13",
		"url": "https://www.youtube.com/watch?v=J8Cp-zm7TLQ", // https://www.youtube.com/watch?v=1KkpivEsitE",
		"title": "Pulp Kitchen",
		"blurb": "Tonight Feed Me Films are running ‘Pulp Kitchen’. A menu of Pulp Fiction inspired drinks and snacks has been designed to immersive viewers in the film’s sensory landscape.",
		"visible": false,
		"lat": 51.498042,
		"long": -0.080688,
		"open": false,
		"starts": 204,
		"ends": 304,
		"next_item": 8,
		"category": "reel",
		"next_item_title": "Explore other transforming urban spaces"
	},
	"14": {
		"id": "14",
		"url": "https://www.youtube.com/watch?v=FloTVEpRyYY",
		"title": "Latitudinal Cuisine",
		"blurb": "Latitudinal Cuisine is a regular supper club with the tag line ‘meet local, eat global’. Each day of the year is assigned a different longitude and latitude around which the events are usually themed. Tonight’s dinner, however, is themed more generally around travel and includes a performance from the band ‘Safar’ which means travel in Arabic. ",
		"visible": false,
		"lat": 51.529199,
		"long": -0.075661,
		"open": false,
		"starts": 145,
		"ends": 245,
		"next_item": 1,
		"category": "edible",
		"next_item_title": "Open more of London's closed doors..."
	},
	"15": {
		"id": "15",
		"url": "https://www.youtube.com/watch?v=bIt8X-vPINw", //https://www.youtube.com/watch?v=nxI_TOg4rA8",
		"title": "Paradise Yard",
		"blurb": "Alfie runs Paradise Yard where small creative businesses occupy shipping containers and a converted school house. ",
		"visible": false,
		"lat": 51.497625,
		"long": -0.115509,
		"open": false,
		"starts": 142,
		"ends": 242,
		"next_item": 8,
		"category": "container",
		"next_item_title": "Explore other transforming urban spaces",
		"outside_the_hidden": "../images/outside/people.jpg",
	},
	"16": {
		"id": "16",
		"url": "https://www.youtube.com/watch?v=RZu64LmCeIE", // Updated
		"title": "Kennington Upholstery ",
		"blurb": "Kennington Upholstery give us a tour of their container and its extension-in-process.",
		"visible": false,
		"lat": 51.497625,
		"long": -0.115509,
		"open": false,
		"starts": 243,
		"ends": 343,
		"next_item": 10,
		"category": "container",
		"next_item_title": "See more ways to customize a container..."
	}
};


module.exports = InitialData;
